version: 2
jobs:
  docker-build:
    docker:
      - image: circleci/buildpack-deps:jessie-curl
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            IMAGE="testrepo573/bitgo-express"
            TAG="$IMAGE:$(cat ./bitgo-express-version)"
            docker build . -t "$TAG"
            if [[ $CIRCLE_BRANCH == "master" ]]; then
               docker tag "$TAG" "$IMAGE":latest
               docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
               docker push "$IMAGE"
            fi

workflows:
  version: 2
  docker-build:
    jobs:
      - docker-build
